FROM alpine:edge

ENV PYENV_ROOT="/.pyenv" \
    PATH="/.pyenv/bin:/.pyenv/shims:$PATH"

RUN apk update && \
	apk add --update --no-cache bash && \
	ln -sf /bin/bash /bin/sh

ENV PYTHONUNBUFFERED = 1
RUN apk add --update --no-cache python3 && \
    ln -sf python3 /usr/bin/python && \
    python3 -m ensurepip && \
    pip3 install --no-cache --upgrade pip setuptools

# alpine-sdk

RUN apk add --no-cache su-exec curl git build-base && \
	apk add --no-cache bzip2-dev libffi-dev ncurses-dev openssl-dev readline-dev sqlite-dev tk-dev xz-dev zlib-dev && \
	curl -s -S -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash

COPY ./tests/python-versions.txt /
RUN pyenv update && \
    xargs -P 4 -n 1 pyenv install < /python-versions.txt && \
    pyenv rehash && \
    rm /python-versions.txt

# pyenv global $(pyenv versions --bare | head -n 1) && \

RUN python -m pip install -v "tox<4.0" "tox-pyenv==1.1.0"

WORKDIR /app

COPY ./amqttrpc/ /app/amqttrpc/

COPY ./tests/*.py /app
COPY ./*requirements.txt /app
COPY ./tox.ini /app

RUN pyenv local $(pyenv versions --bare)

COPY ./tests/docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["tox"]
